//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFCATIONS_READ = "MARK_NOTIFCATIONS_READ";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";

//UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const SET_USER_ERRORS = "SET_USER_ERRORS";

export const LOADING_UI = "LOADING_UI";
export const LOADING_USER_UI = "LOADING_USER_UI";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";

export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//DATE REDUCER TYPES
export const SET_POSTS = "SET_POSTS";
export const SET_POST = "SET_POST";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_POST = "POST_POST";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
